name: foreman tests

on:
  push:
    branches: [ main ]

jobs:

  code_testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: install golang
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: run unit tests
      run: go test ./pkg/*.go

    - name: run integration test
      run: ./tests/integration_test.sh
